language: ruby
rvm:
  - 2.3
script: "bundle exec jekyll build"
deploy:
  provider: pages
  github_token: $TRAVIS_GITHUB_TOKEN
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main

branches:
  only:
  - add-travis-ghpages
  - /.*/
